### ISSUE TITLE
Repeat experiments following assignment instructions

### ISSUE THREAD

**Issue by maherou** [PXIONG001/CSCI317#2]
Please read the assignment instructions carefully and repeat your experiments as directed.

**Comment by PXIONG001** [comment]
Hi DH,

Sorry for not sending this file to you! I got sidetracked by a lot of things that happened this week, but I am not going to make any lame excuses to you. Let me know if you need me to change or redo the assignment for #2. The updated report is the pdf version. Sorry about that DH!
